server:
  port: 8081

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3307/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    view:
      suffix: classpath:/templates/

#      prefix: .html

# mybatis config
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.vueblog.demo.model
  global-config:
    db-config:
      id-type: auto
      #日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
