
server:
  port: 9000

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3307/blogtest?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

# mybatis config
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.blog.demo
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#  redis:
#    host: localhost # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: # Redis服务器连接密码（默认为空）
#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 3000ms # 连接超时时间（毫秒）
#
#    key:
#      prefix:
#        authCode: "portal:authCode:"
#      expire:
#        authCode: 120 # 验证码超期时间
