es:
  host: 192.168.147.132
  port: 9200
  scheme: http

spring:
  rabbitmq:
    port: 5672
    username: mq
    password: 123
    host: localhost
    virtual-host: mqtest
    publisher-returns: true
    publisher-confirm-type: correlated

  jackson:
    #时区，默认为格林尼治时间，即少8小时，所以我们需要+8
    time-zone: GMT+8
    #时间格式转换定义
    date-format: yyyy-MM-dd HH:mm:ss